/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.owsb.poms.ui.im;

import com.owsb.poms.system.model.*;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.EnumSet;
import java.util.List;
import java.util.Set;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class InventoryManagerDashboard extends javax.swing.JFrame { 
    
    private DefaultTableModel modelItems = new DefaultTableModel(){
        public boolean isCellEditable(int row, int column){
           return false;
        }
    };
    private String[] columnItems = {"ItemID", "Name", "Category", "Type", "Stock", "Status"};
    
    private DefaultTableModel modelPO = new DefaultTableModel(){
        public boolean isCellEditable(int row, int column){
           return false;
       } 
    };
    private String[] columnPO = {"Purchase Order ID", "Purchase Requisition ID", "Item ID", "Quantity","Supplier ID", "Delivery Date"};
    
    private final DefaultTableModel modelStockReport = new DefaultTableModel(){
        public boolean isCellEditable(int row, int column){
           return false;
       } 
    };
    private final String[] columnStockReport = {"ReportID", "Date", "Time"};
    
    private final String[] cmbSelection = {"Current Status","Sufficient","Shortage"};
    private final DefaultComboBoxModel<String> modelStatus = new DefaultComboBoxModel<>(cmbSelection);
    
    private int selectedRowItem = -1;
    private int selectedRowPO = -1;
    
    private Item selectedItem = new Item();
    private PurchaseOrder selectedPO = new PurchaseOrder();
    
    private List<Item> itemList;
    private List<Supplier> supplierList;
    private List<PurchaseOrder> POList;
    private List<Report> StockReportList;
    
    DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("dd MMM uuuu");
    DateTimeFormatter timeFormatter = DateTimeFormatter.ofPattern("HH:mm:ss");

    
    /**
     * Creates new form InventoryManagerDashboard
     */
    public InventoryManagerDashboard() {
        initComponents();
        modelItems.setColumnIdentifiers(columnItems);  
        modelPO.setColumnIdentifiers(columnPO);
        modelStockReport.setColumnIdentifiers(columnStockReport);
        ItemTab();
        POTab();
        StockTab();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        tabPanel = new javax.swing.JTabbedPane();
        pnlHome = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        pnlItems = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableItems = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblCategory = new javax.swing.JLabel();
        lblType = new javax.swing.JLabel();
        txtStocks = new java.awt.TextField();
        cmbStatus = new javax.swing.JComboBox<>();
        checkboxConfirmation = new javax.swing.JCheckBox();
        btnEdit = new javax.swing.JButton();
        btnRefreshItems = new javax.swing.JButton();
        btnGenerate = new javax.swing.JButton();
        pnlPO = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePO = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblPOID = new javax.swing.JLabel();
        lblPRID = new javax.swing.JLabel();
        lblItemID = new javax.swing.JLabel();
        lblItemName = new javax.swing.JLabel();
        lblQuantity = new javax.swing.JLabel();
        lblSupplierID = new javax.swing.JLabel();
        lblSupplierName = new javax.swing.JLabel();
        checkboxVerify = new javax.swing.JCheckBox();
        btnVerify = new javax.swing.JButton();
        btnRefreshPO = new javax.swing.JButton();
        pnlStockReport = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableStockReportList = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1210, 810));

        mainPanel.setBackground(new java.awt.Color(204, 204, 255));
        mainPanel.setPreferredSize(new java.awt.Dimension(1210, 810));

        tabPanel.setBackground(new java.awt.Color(255, 153, 153));
        tabPanel.setForeground(new java.awt.Color(0, 0, 0));
        tabPanel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        pnlHome.setBackground(new java.awt.Color(255, 204, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("OWSB Inventory Management");

        btnLogout.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnLogout.setText("Log Out");

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addGap(271, 271, 271)
                .addComponent(jLabel2)
                .addContainerGap(285, Short.MAX_VALUE))
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHomeLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(245, 245, 245)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(378, Short.MAX_VALUE))
        );

        tabPanel.addTab("Home", pnlHome);

        pnlItems.setBackground(new java.awt.Color(255, 204, 255));

        tableItems.setModel(modelItems);
        tableItems.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tableItemsMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tableItems);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Item ID: ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Item Name: ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Category: ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Type: ");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Stocks: ");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Status:");

        lblID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblID.setForeground(new java.awt.Color(0, 0, 0));
        lblID.setText("- ");

        lblName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblName.setForeground(new java.awt.Color(0, 0, 0));
        lblName.setText("- ");

        lblCategory.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCategory.setForeground(new java.awt.Color(0, 0, 0));
        lblCategory.setText("-");

        lblType.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblType.setForeground(new java.awt.Color(0, 0, 0));
        lblType.setText("-");

        txtStocks.setEnabled(false);
        txtStocks.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        cmbStatus.setBackground(new java.awt.Color(255, 255, 255));
        cmbStatus.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbStatus.setModel(modelStatus);
        cmbStatus.setEnabled(false);

        checkboxConfirmation.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        checkboxConfirmation.setText("Tick to confirm modification");
        checkboxConfirmation.setEnabled(false);
        checkboxConfirmation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxConfirmationActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(255, 102, 102));
        btnEdit.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(0, 0, 0));
        btnEdit.setText("Edit");
        btnEdit.setEnabled(false);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnRefreshItems.setBackground(new java.awt.Color(255, 102, 102));
        btnRefreshItems.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRefreshItems.setForeground(new java.awt.Color(0, 0, 0));
        btnRefreshItems.setText("Refresh");
        btnRefreshItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshItemsActionPerformed(evt);
            }
        });

        btnGenerate.setBackground(new java.awt.Color(255, 102, 102));
        btnGenerate.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnGenerate.setForeground(new java.awt.Color(0, 0, 0));
        btnGenerate.setText("Generate Report");
        btnGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlItemsLayout = new javax.swing.GroupLayout(pnlItems);
        pnlItems.setLayout(pnlItemsLayout);
        pnlItemsLayout.setHorizontalGroup(
            pnlItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlItemsLayout.createSequentialGroup()
                .addContainerGap(1097, Short.MAX_VALUE)
                .addComponent(btnRefreshItems)
                .addGap(20, 20, 20))
            .addGroup(pnlItemsLayout.createSequentialGroup()
                .addGroup(pnlItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlItemsLayout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(btnGenerate))
                    .addGroup(pnlItemsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnlItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlItemsLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlItemsLayout.createSequentialGroup()
                                        .addGroup(pnlItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(18, 18, 18)
                                        .addGroup(pnlItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblType)
                                            .addComponent(lblCategory)
                                            .addComponent(lblName)
                                            .addComponent(lblID)
                                            .addComponent(txtStocks, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(checkboxConfirmation)))
                            .addGroup(pnlItemsLayout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlItemsLayout.setVerticalGroup(
            pnlItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlItemsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2)
                    .addGroup(pnlItemsLayout.createSequentialGroup()
                        .addComponent(btnRefreshItems)
                        .addGap(3, 3, 3)
                        .addGroup(pnlItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblID, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(60, 60, 60)
                        .addGroup(pnlItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblName, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(60, 60, 60)
                        .addGroup(pnlItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCategory, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(60, 60, 60)
                        .addGroup(pnlItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblType, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addGroup(pnlItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStocks, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(55, 55, 55)
                        .addGroup(pnlItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(checkboxConfirmation)
                        .addGap(50, 50, 50)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGenerate, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        tabPanel.addTab("Items", pnlItems);

        pnlPO.setBackground(new java.awt.Color(255, 204, 255));
        pnlPO.setMaximumSize(new java.awt.Dimension(1210, 810));

        tablePO.setModel(modelPO);
        tablePO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tablePOMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tablePO);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Purchase Order ID:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Purchase Requisition ID: ");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Item ID: ");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Item Name: ");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Quantity: ");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Supplier ID:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Supplier Name: ");

        lblPOID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPOID.setForeground(new java.awt.Color(0, 0, 0));
        lblPOID.setText("-");

        lblPRID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPRID.setForeground(new java.awt.Color(0, 0, 0));
        lblPRID.setText("-");

        lblItemID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblItemID.setForeground(new java.awt.Color(0, 0, 0));
        lblItemID.setText("-");

        lblItemName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblItemName.setForeground(new java.awt.Color(0, 0, 0));
        lblItemName.setText("-");

        lblQuantity.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblQuantity.setForeground(new java.awt.Color(0, 0, 0));
        lblQuantity.setText("-");

        lblSupplierID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSupplierID.setForeground(new java.awt.Color(0, 0, 0));
        lblSupplierID.setText("-");

        lblSupplierName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSupplierName.setForeground(new java.awt.Color(0, 0, 0));
        lblSupplierName.setText("-");

        checkboxVerify.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        checkboxVerify.setForeground(new java.awt.Color(0, 0, 0));
        checkboxVerify.setText("Tick to Confirm");
        checkboxVerify.setEnabled(false);
        checkboxVerify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxVerifyActionPerformed(evt);
            }
        });

        btnVerify.setBackground(new java.awt.Color(255, 102, 102));
        btnVerify.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnVerify.setForeground(new java.awt.Color(0, 0, 0));
        btnVerify.setText("Verify");
        btnVerify.setEnabled(false);
        btnVerify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerifyActionPerformed(evt);
            }
        });

        btnRefreshPO.setBackground(new java.awt.Color(255, 102, 102));
        btnRefreshPO.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRefreshPO.setForeground(new java.awt.Color(0, 0, 0));
        btnRefreshPO.setText("Refresh");
        btnRefreshPO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshPOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPOLayout = new javax.swing.GroupLayout(pnlPO);
        pnlPO.setLayout(pnlPOLayout);
        pnlPOLayout.setHorizontalGroup(
            pnlPOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPOLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlPOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPOLayout.createSequentialGroup()
                        .addGroup(pnlPOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPOLayout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(btnVerify, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlPOLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlPOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(checkboxVerify))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlPOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPOID)
                                    .addComponent(lblPRID)
                                    .addComponent(lblItemID)
                                    .addComponent(lblItemName)
                                    .addComponent(lblQuantity)
                                    .addComponent(lblSupplierID)
                                    .addComponent(lblSupplierName))))
                        .addContainerGap(118, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPOLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRefreshPO)
                        .addGap(32, 32, 32))))
        );
        pnlPOLayout.setVerticalGroup(
            pnlPOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPOLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPOLayout.createSequentialGroup()
                        .addGap(0, 13, Short.MAX_VALUE)
                        .addComponent(btnRefreshPO)
                        .addGap(17, 17, 17)
                        .addGroup(pnlPOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(lblPOID))
                        .addGap(40, 40, 40)
                        .addGroup(pnlPOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(lblPRID))
                        .addGap(40, 40, 40)
                        .addGroup(pnlPOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(lblItemID))
                        .addGap(40, 40, 40)
                        .addGroup(pnlPOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(lblItemName))
                        .addGap(40, 40, 40)
                        .addGroup(pnlPOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(lblQuantity))
                        .addGap(40, 40, 40)
                        .addGroup(pnlPOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(lblSupplierID))
                        .addGap(40, 40, 40)
                        .addGroup(pnlPOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(lblSupplierName))
                        .addGap(45, 45, 45)
                        .addComponent(checkboxVerify)
                        .addGap(97, 97, 97)
                        .addComponent(btnVerify, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))
                    .addGroup(pnlPOLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );

        tabPanel.addTab("Purchase Order", pnlPO);

        pnlStockReport.setBackground(new java.awt.Color(255, 204, 255));

        tableStockReportList.setModel(modelStockReport);
        tableStockReportList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableStockReportListMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableStockReportList);

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlStockReportLayout = new javax.swing.GroupLayout(pnlStockReport);
        pnlStockReport.setLayout(pnlStockReportLayout);
        pnlStockReportLayout.setHorizontalGroup(
            pnlStockReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStockReportLayout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStockReportLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(517, 517, 517))
        );
        pnlStockReportLayout.setVerticalGroup(
            pnlStockReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStockReportLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        tabPanel.addTab("Stock Reports", pnlStockReport);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(tabPanel)
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPanel)
        );

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tableItemsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableItemsMouseReleased

        cmbStatus.setSelectedIndex(-1);
        checkboxConfirmation.setSelected(false);
        btnEdit.setEnabled(false);
        
        selectedRowItem = tableItems.getSelectedRow();
        
        selectedItem.setItemID(String.valueOf(modelItems.getValueAt(selectedRowItem, 0)));
        selectedItem.setItemName(String.valueOf(modelItems.getValueAt(selectedRowItem, 1)));
        selectedItem.setItemCategory(String.valueOf(modelItems.getValueAt(selectedRowItem, 2)));
        selectedItem.setItemType(String.valueOf(modelItems.getValueAt(selectedRowItem, 3)));
        selectedItem.setStock(Integer.parseInt(String.valueOf(modelItems.getValueAt(selectedRowItem, 4))));
        selectedItem.setStatus(Item.Status.valueOf(String.valueOf(modelItems.getValueAt(selectedRowItem, 5))));
        
        String uppercase = selectedItem.getStatus().name();
        String status = uppercase.substring(0, 1).toUpperCase() + uppercase.substring(1).toLowerCase();
        
        lblID.setText(selectedItem.getItemID());
        lblName.setText(selectedItem.getItemName());
        lblCategory.setText(selectedItem.getItemCategory());
        lblType.setText(selectedItem.getItemType());
        txtStocks.setText(String.valueOf(selectedItem.getStock()));       
        cmbStatus.setSelectedItem(status);
        
        txtStocks.enable(true);
        cmbStatus.enable(true);
        checkboxConfirmation.setEnabled(true);
    }//GEN-LAST:event_tableItemsMouseReleased

    private void checkboxConfirmationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxConfirmationActionPerformed
        if(checkboxConfirmation.isSelected()){
            btnEdit.setEnabled(true);
        }
        else{
            btnEdit.setEnabled(false);
        }
    }//GEN-LAST:event_checkboxConfirmationActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        
        int newQuantity;
        
        String status = String.valueOf(cmbStatus.getSelectedItem());
        Item.Status newStatus;
        
        try {
           newQuantity = Integer.parseInt(txtStocks.getText());
            if (newQuantity < 0){
                JOptionPane.showMessageDialog(this, "Please enter a valid Number");
                return;
            }
        } catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Please enter a valid number");
            return;
        }      
        
        newStatus = switch (status) {
            case "Sufficient" -> Item.Status.SUFFICIENT;
            case "Shortage" -> Item.Status.SHORTAGE;
            default -> selectedItem.getStatus();
        };
        
        selectedItem.setStock(newQuantity);
        selectedItem.updateStock(); 
        selectedItem.setStatus(newStatus);
        selectedItem.updateStatus();

        ItemTab();
    }//GEN-LAST:event_btnEditActionPerformed

    // ItemTabRefresh
    private void ItemTab(){
        modelItems.setRowCount(0);
        
        lblID.setText("-");
        lblName.setText("-");
        lblCategory.setText("-");
        lblType.setText("-");
        txtStocks.setText("");
        cmbStatus.setSelectedIndex(-1);
      
        tableItems.getColumnModel().getColumn(0).setPreferredWidth(10);
        tableItems.getColumnModel().getColumn(1).setPreferredWidth(200);

       
        itemList = Item.toList();
        
        for (Item eachItem : itemList) {
            if (eachItem.getStatus() != Item.Status.REMOVED){
                modelItems.addRow(new String[]{
                    eachItem.getItemID(),
                    eachItem.getItemName(),
                    eachItem.getItemCategory(),
                    eachItem.getItemType(),
                    String.valueOf(eachItem.getStock()),
                    eachItem.getStatus().name()
                });
            }
        }
        
        btnEdit.setEnabled(false);
        txtStocks.enable(false);
        checkboxConfirmation.setSelected(false);
        checkboxConfirmation.setEnabled(false);
        cmbStatus.enable(false);
        tableItems.clearSelection();
        selectedRowItem = -1;
    }
    
    
    private void tablePOMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePOMouseReleased

        supplierList = Supplier.toList();
        
        checkboxVerify.setSelected(false);
        btnVerify.setEnabled(false);
        
        selectedRowPO = tablePO.getSelectedRow();

        selectedPO.setPOID(String.valueOf(modelPO.getValueAt(selectedRowPO, 0)));
        selectedPO.setPRID(String.valueOf(modelPO.getValueAt(selectedRowPO, 1)));
//        selectedPO.setItemID(String.valueOf(modelPO.getValueAt(selectedRowItem, 2)));
//        String itemName = getItemNameByID(selectedPO.getItemID(), itemList);
//        selectedPO.setItemName(itemName);
//        selectedPO.setQuantity(Integer.parseInt(String.valueOf(modelPO.getValueAt(selectedRowItem, 3))));
        selectedPO.setSupplierID(String.valueOf(modelPO.getValueAt(selectedRowPO, 4)));
        String supplierName = getSupplierNameByID(selectedPO.getSupplierID(), supplierList);
        selectedPO.setDeliveryDate(LocalDate.parse(String.valueOf(modelPO.getValueAt(selectedRowPO, 5))));
//        
        lblPOID.setText(selectedPO.getPOID());
        lblPRID.setText(selectedPO.getPRID());
//        lblItemID.setText(selectedPO.getItemID());
//        lblItemName.setText(selectedPO.getItemName());
//        lblQuantity.setText(String.valueOf(selectedPO.getQuantity()));
        lblSupplierID.setText(selectedPO.getSupplierID());
        lblSupplierName.setText(supplierName);
            
        checkboxVerify.setEnabled(true);
    }//GEN-LAST:event_tablePOMouseReleased

    private void checkboxVerifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxVerifyActionPerformed
        if(checkboxVerify.isSelected()){
            btnVerify.setEnabled(true);
        }
        else{
            btnVerify.setEnabled(false);
        }
    }//GEN-LAST:event_checkboxVerifyActionPerformed

    private void btnVerifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerifyActionPerformed
    
//        selectedPO.setStatus(newStatus);
//        selectedPO.updateStatus();
//
//        POTab();
    }//GEN-LAST:event_btnVerifyActionPerformed

    private void btnRefreshItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshItemsActionPerformed
        ItemTab();
    }//GEN-LAST:event_btnRefreshItemsActionPerformed

    private void btnRefreshPOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshPOActionPerformed
        POTab();
    }//GEN-LAST:event_btnRefreshPOActionPerformed
    
    private void POTab(){
          
        modelPO.setRowCount(0);
        
        lblPOID.setText("-");
        lblPRID.setText("-");
        lblItemID.setText("-");
        lblItemName.setText("-");
        lblQuantity.setText("-");
        lblSupplierID.setText("-");
        lblSupplierName.setText("-");
      
//        tablePO.getColumnModel().getColumn(1).setPreferredWidth(100);
//        tablePO.getColumnModel().getColumn(2).setPreferredWidth(100);
//        tablePO.getColumnModel().getColumn(3).setPreferredWidth(150);
//        tablePO.getColumnModel().getColumn(6).setPreferredWidth(100);
       
        POList = PurchaseOrder.toList();
        Set<PurchaseOrder.Status> includedStatuses = EnumSet.of(
            PurchaseOrder.Status.PROCESSING,
            PurchaseOrder.Status.EXTENDED,
            PurchaseOrder.Status.ARRIVED
        );
        
        for (PurchaseOrder eachPO : POList) {
            if (includedStatuses.contains(eachPO.getStatus())){
                modelItems.addRow(new String[]{
                    eachPO.getPOID(),
                    eachPO.getPRID(),
//                    eachPO.getItemID(),
//                    String.valueOf(eachPO.getQuantity()),
                    eachPO.getSupplierID(),
                    eachPO.getDeliveryDate().toString()
                });
            }
        }

        btnVerify.setEnabled(false);
        checkboxConfirmation.setSelected(false);
        checkboxVerify.setEnabled(false);
        tablePO.clearSelection();
        selectedRowPO = -1;
    }
 
    
    private void btnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateActionPerformed
        itemList = Item.toList();
        List<StockReport> reportList = StockReport.generateStockList(itemList);       
        new StockReport().save(reportList);
        JOptionPane.showMessageDialog(this,"Stock report generated" );
        StockTab();
    }//GEN-LAST:event_btnGenerateActionPerformed

    private void tableStockReportListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableStockReportListMouseClicked
        if (evt.getClickCount() == 2 && tableStockReportList.getSelectedRow() != -1) {
            int selectedRow = tableStockReportList.getSelectedRow();

            // Extract data from the selected row
            String id = String.valueOf(tableStockReportList.getValueAt(selectedRow, 0));
            ViewStockReport stockReport = new ViewStockReport(id);
            stockReport.setLocationRelativeTo(this);
            stockReport.setVisible(true);

        }
    }//GEN-LAST:event_tableStockReportListMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        StockTab();
    }//GEN-LAST:event_jButton1ActionPerformed
     
    private void StockTab(){
        modelStockReport.setRowCount(0);
        
        StockReportList = Report.toList();
        
        for (Report eachReport : StockReportList) {
            if (eachReport.getReportID().startsWith("STK")){
                
                String date = dateFormatter.format(eachReport.getDateTime());
                String time = timeFormatter.format(eachReport.getDateTime());
                
                modelStockReport.addRow(new String[]{
                    eachReport.getReportID(),
                    date,
                    time
                });
            }
        }
        
    }
    public static String getItemNameByID(String itemID, List<Item> itemList) {
        for (Item item : itemList) {
            if (item.getItemID().equals(itemID)) {
                return item.getItemName();
            }
        }
        return "-";
    }
    
    public static String getSupplierNameByID(String supplierID, List<Supplier> supplierList){
        for(Supplier supplier: supplierList){
            if(supplier.getSupplierID().equals(supplierID)){
                return supplier.getSupplierName();
            }
        }
        return "-";
    }
    
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InventoryManagerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InventoryManagerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InventoryManagerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InventoryManagerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InventoryManagerDashboard().setVisible(true);
            }
        });
        
  
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnGenerate;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRefreshItems;
    private javax.swing.JButton btnRefreshPO;
    private javax.swing.JButton btnVerify;
    private javax.swing.JCheckBox checkboxConfirmation;
    private javax.swing.JCheckBox checkboxVerify;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblItemID;
    private javax.swing.JLabel lblItemName;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPOID;
    private javax.swing.JLabel lblPRID;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblSupplierID;
    private javax.swing.JLabel lblSupplierName;
    private javax.swing.JLabel lblType;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlItems;
    private javax.swing.JPanel pnlPO;
    private javax.swing.JPanel pnlStockReport;
    private javax.swing.JTabbedPane tabPanel;
    private javax.swing.JTable tableItems;
    private javax.swing.JTable tablePO;
    private javax.swing.JTable tableStockReportList;
    private java.awt.TextField txtStocks;
    // End of variables declaration//GEN-END:variables
}
