package com.owsb.poms.ui.common;

import com.owsb.poms.system.model.User.Admin;
import com.owsb.poms.system.model.User.FinanceManager;
import com.owsb.poms.system.model.User.InventoryManager;
import com.owsb.poms.system.model.User.PurchaseManager;
import com.owsb.poms.system.model.User.SalesManager;
import com.owsb.poms.system.model.User.User;
import java.awt.*;
import java.time.LocalDate;
import javax.swing.JOptionPane;

public class Login extends javax.swing.JFrame {
    private Point initialClick;
    private User user;
    private boolean validUser = false;
    
    public Login() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        new CommonMethod().setFrameIcon("/icons/logo.png", 330, 330, Image.SCALE_SMOOTH, this);
        new CommonMethod().setLabelIcon("/icons/logo.png", 330, 330, Image.SCALE_SMOOTH, lblLogo);
        new CommonMethod().setLabelIcon("/icons/user.png", 25, 25, Image.SCALE_SMOOTH, lblUserIcon);
        new CommonMethod().setLabelIcon("/icons/padlock.png", 25, 25, Image.SCALE_SMOOTH, lblPwdIcon);
    }
    
    private void login(){
        String identifier = txtUser.getText().toUpperCase().trim();
        String password = txtPassword.getText();
        String domain = "@owsb.com.my";
        
        
        var users = User.toList();
        for (User u : users){
            if (u.isIsDeleted() != true){
                if(identifier.equals(u.getUID())){
                    validUser = true;
                    user = User.getUserById(identifier);
                    break;
                }
                
                if(identifier.equals(u.getUsername())){
                    validUser = true;
                    user = User.getUserByName(identifier);
                    break;
                }
                
                if(identifier.length() < domain.length() + 3){
                    continue;
                }
                
                if ((identifier.substring(0, identifier.length() - domain.length()) + domain).equals(u.getEmail())){
                    validUser = true;
                    identifier = identifier.substring(0, identifier.length() - domain.length()) + domain;
                    user = User.getUserByEmail(identifier);
                    break;
                }
            }
        }
        
        if (validUser){
            if (user.getHash(password).equals(user.getPasswordHash())){
                User u = user.getActual();
                switch (user.getRole()){
                    case Root, Admin:
                        Admin admin = (Admin) u;
                        admin.login();
                        dispose();
                        return;
                    case SalesManager:
                        SalesManager sm = (SalesManager) u;
                        sm.login();
                        dispose();
                        return;
                    case PurchaseManager:
                        PurchaseManager pm = (PurchaseManager) u;
                        pm.login();
                        dispose();
                        return;
                    case InventoryManager:
                        InventoryManager im = (InventoryManager) u;
                        im.login();
                        dispose();
                        return;
                    case FinanceManager:
                        FinanceManager fm = (FinanceManager) u;
                        fm.login();
                        dispose();
                        return;
                }
            }
            JOptionPane.showMessageDialog(this, "Invalid Password!", "Error", JOptionPane.ERROR_MESSAGE);
            txtPassword.setText("");
        }
        else{
            JOptionPane.showMessageDialog(this, "Invalid User!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLogo = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        pnlInfo = new javax.swing.JPanel();
        lblClose = new javax.swing.JLabel();
        lblLoginTitle = new javax.swing.JLabel();
        lblUserIcon = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        lblPwdIcon = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("POMS");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(800, 550));
        setName(""); // NOI18N
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlLogo.setBackground(new java.awt.Color(255, 204, 204));
        pnlLogo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlLogoMouseDragged(evt);
            }
        });
        pnlLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlLogoMousePressed(evt);
            }
        });

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setToolTipText("");

        javax.swing.GroupLayout pnlLogoLayout = new javax.swing.GroupLayout(pnlLogo);
        pnlLogo.setLayout(pnlLogoLayout);
        pnlLogoLayout.setHorizontalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLogoLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        pnlLogoLayout.setVerticalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogoLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        getContentPane().add(pnlLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 550));

        pnlInfo.setBackground(new java.awt.Color(253, 221, 221));
        pnlInfo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlInfoMouseDragged(evt);
            }
        });
        pnlInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlInfoMousePressed(evt);
            }
        });
        pnlInfo.setLayout(null);

        lblClose.setBackground(new java.awt.Color(255, 186, 186));
        lblClose.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 24)); // NOI18N
        lblClose.setForeground(new java.awt.Color(0, 0, 0));
        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setText("X");
        lblClose.setOpaque(true);
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCloseMouseExited(evt);
            }
        });
        pnlInfo.add(lblClose);
        lblClose.setBounds(350, 0, 50, 40);

        lblLoginTitle.setFont(new java.awt.Font("Engravers MT", 1, 24)); // NOI18N
        lblLoginTitle.setForeground(new java.awt.Color(0, 0, 0));
        lblLoginTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLoginTitle.setText("Staff Login");
        pnlInfo.add(lblLoginTitle);
        lblLoginTitle.setBounds(70, 50, 270, 75);

        lblUserIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserIcon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlInfo.add(lblUserIcon);
        lblUserIcon.setBounds(60, 170, 25, 25);

        lblUser.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        lblUser.setForeground(new java.awt.Color(0, 0, 0));
        lblUser.setText("UID/Username/Email");
        pnlInfo.add(lblUser);
        lblUser.setBounds(90, 170, 151, 30);

        txtUser.setBackground(new java.awt.Color(250, 236, 236));
        txtUser.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        txtUser.setForeground(new java.awt.Color(0, 0, 0));
        txtUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtUser.setCaretColor(new java.awt.Color(204, 204, 204));
        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });
        pnlInfo.add(txtUser);
        txtUser.setBounds(64, 199, 270, 30);

        lblPwdIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPwdIcon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlInfo.add(lblPwdIcon);
        lblPwdIcon.setBounds(60, 260, 25, 25);

        lblPassword.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(0, 0, 0));
        lblPassword.setText("Password");
        pnlInfo.add(lblPassword);
        lblPassword.setBounds(90, 260, 151, 30);

        txtPassword.setBackground(new java.awt.Color(250, 236, 236));
        txtPassword.setForeground(new java.awt.Color(0, 0, 0));
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        pnlInfo.add(txtPassword);
        txtPassword.setBounds(64, 288, 270, 30);

        btnLogin.setBackground(new java.awt.Color(255, 204, 204));
        btnLogin.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(0, 0, 0));
        btnLogin.setText("Log in");
        btnLogin.setFocusPainted(false);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        pnlInfo.add(btnLogin);
        btnLogin.setBounds(145, 378, 108, 39);

        getContentPane().add(pnlInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 400, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblCloseMouseClicked

    private void lblCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseEntered
        lblClose.setBackground(Color.red);
        lblClose.setForeground(Color.white);
    }//GEN-LAST:event_lblCloseMouseEntered

    private void lblCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseExited
        lblClose.setBackground(new java.awt.Color(255, 186, 186));
        lblClose.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_lblCloseMouseExited

    private void pnlLogoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLogoMousePressed
        initialClick = evt.getPoint();
    }//GEN-LAST:event_pnlLogoMousePressed

    private void pnlLogoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLogoMouseDragged
        CommonEvent.mouseDragWindow(this, evt, initialClick);
    }//GEN-LAST:event_pnlLogoMouseDragged

    private void pnlInfoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlInfoMousePressed
        initialClick = evt.getPoint();
    }//GEN-LAST:event_pnlInfoMousePressed

    private void pnlInfoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlInfoMouseDragged
        CommonEvent.mouseDragWindow(this, evt, initialClick);
    }//GEN-LAST:event_pnlInfoMouseDragged

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        login();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        login();
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        login();
    }//GEN-LAST:event_txtUserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblLoginTitle;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPwdIcon;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblUserIcon;
    private javax.swing.JPanel pnlInfo;
    private javax.swing.JPanel pnlLogo;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
