package com.owsb.poms.ui.admin.Orders;

import com.owsb.poms.system.functions.UserValidation;
import com.owsb.poms.system.model.*;
import com.owsb.poms.system.model.User.*;
import java.util.List;
import java.util.stream.*;
import javax.swing.*;

public class OrderReport extends javax.swing.JDialog {
    PurchaseOrder po;
    JDialog parent;
    List<Transaction> transactions;

    public OrderReport(javax.swing.JDialog parent, boolean modal, PurchaseOrder po) {
        super(parent, modal);
        initComponents();
        
        this.parent = parent;
        this.po = po;
        this.transactions = po.getTransactions();
        
        lblPOID.setText(po.getPOID());
        
        String trs = IntStream.range(0, transactions.size())
        .mapToObj(i -> String.format(
            "%d.%s<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Amount: RM %.2f<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Processed By: %s %s",
            i + 1,
            transactions.get(i).getTransactionID(),
            transactions.get(i).getAmount(),
            transactions.get(i).getProcessBy(), 
            User.getUserById(transactions.get(i).getProcessBy()).getUsername()
            ))
        .collect(Collectors.joining("<br><br>"));
        
        lblTransactions.setText("<html>" + trs + "</html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblPOID = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtInvoiceID = new javax.swing.JTextField();
        btnGenerateReport = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMessage = new javax.swing.JTextArea();
        btnCancel = new javax.swing.JButton();
        txtVerifiedBy = new javax.swing.JTextField();
        lblTransactions = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlMain.setBackground(new java.awt.Color(244, 213, 188));

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Purchase Report");

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("ID:");

        lblPOID.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        lblPOID.setForeground(new java.awt.Color(0, 0, 0));
        lblPOID.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPOID.setText("[POID]");

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Transactions:");

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Invoice ID:");

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Verified By:");

        btnGenerateReport.setBackground(new java.awt.Color(255, 153, 0));
        btnGenerateReport.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        btnGenerateReport.setForeground(new java.awt.Color(252, 251, 249));
        btnGenerateReport.setText("Generate Report");
        btnGenerateReport.setToolTipText("");
        btnGenerateReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateReportActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Report Message:");

        txtMessage.setColumns(20);
        txtMessage.setRows(5);
        jScrollPane1.setViewportView(txtMessage);

        btnCancel.setBackground(new java.awt.Color(255, 153, 0));
        btnCancel.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(252, 251, 249));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        lblTransactions.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        lblTransactions.setForeground(new java.awt.Color(0, 0, 0));
        lblTransactions.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTransactions.setText("[Transactions]");
        lblTransactions.setToolTipText("");

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel16)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(86, 86, 86)
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblPOID)
                                .addComponent(txtInvoiceID, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                                .addComponent(txtVerifiedBy, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE))
                            .addComponent(lblTransactions, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGenerateReport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(26, 26, 26)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblPOID))
                .addGap(18, 59, Short.MAX_VALUE)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblTransactions))
                .addGap(18, 59, Short.MAX_VALUE)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInvoiceID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 62, Short.MAX_VALUE)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVerifiedBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 62, Short.MAX_VALUE)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGenerateReport, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32))
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerateReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateReportActionPerformed
        String invoiceID = txtInvoiceID.getText().trim();
        String verifiedBy = txtVerifiedBy.getText().toUpperCase().trim();
        String message = txtMessage.getText().trim();
        
        if (invoiceID.isBlank()){
            JOptionPane.showMessageDialog(this, "Invoice ID is required. Please enter it.", "Oops! Something's Missing", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (verifiedBy.isBlank()){
            JOptionPane.showMessageDialog(this, "This order verified by who is required. Please enter it.", "Oops! Something's Missing", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (message.isBlank()){
            JOptionPane.showMessageDialog(this, "Report message is required. Please enter it.", "Oops! Something's Missing", JOptionPane.ERROR_MESSAGE);
            return; 
        }
        
        if (!UserValidation.exitedId(verifiedBy)){
            User u = User.getUserBySimilarName(verifiedBy);
            if (u != null){
                JOptionPane.showMessageDialog(
                        this, 
                        String.format(
                                "Please type the UID of the user! You might mean %s (%s)", 
                                u.getUID(),
                                u.getUsername()
                        ), 
                        "UID Required",  
                        JOptionPane.ERROR_MESSAGE
                );
                return; 
            }   
            JOptionPane.showMessageDialog(
                    this, 
                    "Invalid UID. Please enter the UID of a person who verified this order.", 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        
        int result = JOptionPane.showConfirmDialog(this, "Are you sure to generate a purchase report?", "Generate Purchase Report", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (result == JOptionPane.YES_OPTION){
                PurchaseReport purchaseReport = new PurchaseReport(po.getPOID(), invoiceID, verifiedBy, message);
                purchaseReport.add();
                
                po.setStatus(PurchaseOrder.Status.REPORTED);
                po.updateStatus();
                
                JOptionPane.showMessageDialog(this, String.format("Report %s has generated!", purchaseReport.getReportID()));
                dispose();
                parent.dispose();
            }
    }//GEN-LAST:event_btnGenerateReportActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnGenerateReport;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPOID;
    private javax.swing.JLabel lblTransactions;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JTextField txtInvoiceID;
    private javax.swing.JTextArea txtMessage;
    private javax.swing.JTextField txtVerifiedBy;
    // End of variables declaration//GEN-END:variables
}
