package com.owsb.poms.ui.admin.Orders;

import com.owsb.poms.system.model.*;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

public class POList extends javax.swing.JDialog {
    private Admin admin;
    private List<PurchaseOrder> poList;
    private DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
    private DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
    
    private DefaultTableModel poModel = new DefaultTableModel(){
       public boolean isCellEditable(int row, int column){
           return false;
       } 
    } ;
    private String[] poColumnName = {"ID", "From", "Supplier", "Total Price", "Delivery Date", "Created By", "Status"};

    public POList(java.awt.Frame parent, boolean modal, Admin admin) {
        super(parent, modal);
        initComponents();
        
        this.admin = admin;
        setTitle("Purchase Orders");
        
        cbAllPOs.setSelected(true);
        
        PO();
    }

    private void PO(){
        
        poModel.setRowCount(0);
        
        poModel.setColumnIdentifiers(poColumnName);
        JTableHeader header = tblPR.getTableHeader();
        header.setBackground(new java.awt.Color(255, 255, 204));
        
        srlPR.getViewport().setBackground(new java.awt.Color(255, 255, 204));
        
        tblPR.getColumnModel().getColumn(2).setPreferredWidth(150);
        
        poList = PurchaseOrder.toList();
        
        for (PurchaseOrder po : poList) {
            poModel.addRow(new String[]{
                po.getPRID(),
                po.getPRID(),
                po.getSupplierID(),
                String.format("%2f", po.getTotalPrice()),
                po.getDeliveryDate().format(dateFormatter),
                po.getCreateBy(),
                po.getStatus().name()
            });
        }
        
        // Create a single “center” renderer:
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);

        // Apply it as the default for any Object‐typed cell:
        tblPR.setDefaultRenderer(Object.class, centerRenderer);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        srlPR = new javax.swing.JScrollPane();
        tblPR = new javax.swing.JTable();
        btnNew = new javax.swing.JButton();
        cbAllPOs = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlMain.setBackground(new java.awt.Color(255, 204, 204));

        tblPR.setBackground(new java.awt.Color(255, 255, 204));
        tblPR.setForeground(new java.awt.Color(0, 0, 0));
        tblPR.setModel(poModel);
        tblPR.setGridColor(java.awt.Color.gray);
        tblPR.setSelectionBackground(new java.awt.Color(255, 153, 153));
        tblPR.setShowGrid(true);
        tblPR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPRMouseClicked(evt);
            }
        });
        srlPR.setViewportView(tblPR);

        btnNew.setBackground(new java.awt.Color(204, 204, 255));
        btnNew.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        btnNew.setForeground(new java.awt.Color(0, 0, 0));
        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        cbAllPOs.setBackground(new java.awt.Color(204, 204, 255));
        cbAllPOs.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        cbAllPOs.setForeground(new java.awt.Color(0, 0, 0));
        cbAllPOs.setLabel("All POs");
        cbAllPOs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAllPOsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                .addContainerGap(856, Short.MAX_VALUE)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cbAllPOs, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(btnNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33))
            .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlMainLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(srlPR, javax.swing.GroupLayout.PREFERRED_SIZE, 813, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(cbAllPOs)
                .addContainerGap(602, Short.MAX_VALUE))
            .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlMainLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(srlPR, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblPRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPRMouseClicked
        if (evt.getClickCount() == 2 && tblPR.getSelectedRow() != -1) {
            
        }
    }//GEN-LAST:event_tblPRMouseClicked

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        POModifier newPO = new POModifier(this, true, admin);
        newPO.setLocationRelativeTo(this);
        newPO.setVisible(true);
        PO();
    }//GEN-LAST:event_btnNewActionPerformed

    private void cbAllPOsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAllPOsActionPerformed
        
    }//GEN-LAST:event_cbAllPOsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNew;
    private javax.swing.JCheckBox cbAllPOs;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JScrollPane srlPR;
    private javax.swing.JTable tblPR;
    // End of variables declaration//GEN-END:variables
}
