package com.owsb.poms.ui.admin.Orders;

import com.owsb.poms.system.model.*;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.SwingConstants;
import javax.swing.table.*;

public class PRList extends javax.swing.JDialog {
    private String userID;
    private List<PurchaseRequisition> prList;
    private DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
    private DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
    
    private DefaultTableModel prModel = new DefaultTableModel(){
       public boolean isCellEditable(int row, int column){
           return false;
       } 
    } ;
    private String[] prColumnName = {"ID", "Supplier", "Date Time", "Required Delivery On", "Created By", "Status"};
   

    /**
     * Creates new form PRList
     */
    public PRList(java.awt.Frame parent, boolean modal, String userID) {
        super(parent, modal);
        initComponents();
        
        this.userID = userID;
        setTitle("Purchase Requisitions");
        
        PR();
    }
    
    private void PR(){
        
        prModel.setRowCount(0);
        
        prModel.setColumnIdentifiers(prColumnName);
        JTableHeader header = tblPR.getTableHeader();
        header.setBackground(new java.awt.Color(255, 255, 204));
        
        srlPR.getViewport().setBackground(new java.awt.Color(255, 255, 204));
        
        tblPR.getColumnModel().getColumn(2).setPreferredWidth(150);
        
        prList = PurchaseRequisition.toList();
        
        for (PurchaseRequisition pr : prList) {
            if (cbShowAllPr.isSelected() || pr.getStatus() == PurchaseRequisition.Status.NEW) {
                prModel.addRow(new String[]{
                    pr.getPRID(),
                    pr.getSupplierID(),
                    pr.getRequestDateTime().format(dateTimeFormatter),
                    pr.getRequiredDeliveryDate().format(dateFormatter),
                    pr.getCreateBy(),
                    pr.getStatus().name()
                });
            }
        }
        
        // Create a single “center” renderer:
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);

        // Apply it as the default for any Object‐typed cell:
        tblPR.setDefaultRenderer(Object.class, centerRenderer);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        srlPR = new javax.swing.JScrollPane();
        tblPR = new javax.swing.JTable();
        btnNew = new javax.swing.JButton();
        cbShowAllPr = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlMain.setBackground(new java.awt.Color(255, 204, 204));

        tblPR.setBackground(new java.awt.Color(255, 255, 204));
        tblPR.setForeground(new java.awt.Color(0, 0, 0));
        tblPR.setModel(prModel);
        tblPR.setGridColor(java.awt.Color.gray);
        tblPR.setSelectionBackground(new java.awt.Color(255, 153, 153));
        tblPR.setShowGrid(true);
        tblPR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPRMouseClicked(evt);
            }
        });
        srlPR.setViewportView(tblPR);

        btnNew.setBackground(new java.awt.Color(204, 204, 255));
        btnNew.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        btnNew.setForeground(new java.awt.Color(0, 0, 0));
        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        cbShowAllPr.setBackground(new java.awt.Color(204, 204, 255));
        cbShowAllPr.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        cbShowAllPr.setForeground(new java.awt.Color(0, 0, 0));
        cbShowAllPr.setText("Show All PRs");
        cbShowAllPr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbShowAllPrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                .addContainerGap(856, Short.MAX_VALUE)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cbShowAllPr, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(btnNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33))
            .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlMainLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(srlPR, javax.swing.GroupLayout.PREFERRED_SIZE, 813, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(175, Short.MAX_VALUE)))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(cbShowAllPr)
                .addContainerGap(602, Short.MAX_VALUE))
            .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlMainLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(srlPR, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblPRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPRMouseClicked
        if (evt.getClickCount() == 2 && tblPR.getSelectedRow() != -1) {
            int row = tblPR.getSelectedRow();
            
            PurchaseRequisition pr = new PurchaseRequisition();
            pr.setPRID(String.valueOf(tblPR.getValueAt(row, 0)));
            pr.setSupplierID(String.valueOf(tblPR.getValueAt(row, 1)));
            pr.setRequestDateTime(LocalDateTime.parse(String.valueOf(tblPR.getValueAt(row, 2)), dateTimeFormatter));
            pr.setRequiredDeliveryDate(LocalDate.parse(String.valueOf(tblPR.getValueAt(row, 3)), dateFormatter));
            pr.setCreateBy(String.valueOf(tblPR.getValueAt(row, 4)));
            pr.setStatus(PurchaseRequisition.Status.valueOf(String.valueOf(tblPR.getValueAt(row, 5))));
            
            PRDetails prd = new PRDetails(this, true, pr, userID);
            prd.setLocationRelativeTo(this);
            prd.setVisible(true);
            PR();
        }
    }//GEN-LAST:event_tblPRMouseClicked

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        PRModifier newPR = new PRModifier(this, true, userID);
        newPR.setLocationRelativeTo(this);
        newPR.setVisible(true);
        PR();
    }//GEN-LAST:event_btnNewActionPerformed

    private void cbShowAllPrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbShowAllPrActionPerformed
        if (cbShowAllPr.isSelected()){
            PR();
        }
        else{
            PR();
        }
    }//GEN-LAST:event_cbShowAllPrActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNew;
    private javax.swing.JCheckBox cbShowAllPr;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JScrollPane srlPR;
    private javax.swing.JTable tblPR;
    // End of variables declaration//GEN-END:variables
}
