package com.owsb.poms.ui.admin.Orders;

import com.owsb.poms.system.model.*;
import java.util.List;
import javax.swing.SwingConstants;
import javax.swing.table.*;

public class PRList extends javax.swing.JDialog {
    private String username;
    private int selectedPrRow;
    private PurchaseRequisition selectedPr = new PurchaseRequisition();
    private List<PurchaseRequisition> prList;
    private DefaultTableModel prModel = new DefaultTableModel(){
       public boolean isCellEditable(int row, int column){
           return false;
       } 
    } ;
    private String[] prColumnName = {"ID", "Supplier", "Date Time", "Required Delivery On", "Created By", "Status"};
   

    /**
     * Creates new form PRList
     */
    public PRList(java.awt.Frame parent, boolean modal, String username) {
        super(parent, modal);
        initComponents();
        
        this.username = username;
        setTitle("Purchase Requisitions");
        
        PR();
    }
    
    private void PR(){
        selectedPrRow = -1;
        prModel.setRowCount(0);
        
        prModel.setColumnIdentifiers(prColumnName);
        JTableHeader header = tblPR.getTableHeader();
        header.setBackground(new java.awt.Color(255, 255, 204));
        
        srlPR.getViewport().setBackground(new java.awt.Color(255, 255, 204));
        
        tblPR.getColumnModel().getColumn(3).setPreferredWidth(150);
        
        // Create a single “center” renderer:
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);

        // Apply it as the default for any Object‐typed cell:
        tblPR.setDefaultRenderer(Object.class, centerRenderer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        srlPR = new javax.swing.JScrollPane();
        tblPR = new javax.swing.JTable();
        btnNew = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlMain.setBackground(new java.awt.Color(255, 204, 204));

        tblPR.setBackground(new java.awt.Color(255, 255, 204));
        tblPR.setForeground(new java.awt.Color(0, 0, 0));
        tblPR.setModel(prModel);
        tblPR.setGridColor(java.awt.Color.gray);
        tblPR.setSelectionBackground(new java.awt.Color(255, 153, 153));
        tblPR.setShowGrid(true);
        tblPR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPRMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblPRMouseReleased(evt);
            }
        });
        srlPR.setViewportView(tblPR);

        btnNew.setBackground(new java.awt.Color(204, 204, 255));
        btnNew.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        btnNew.setForeground(new java.awt.Color(0, 0, 0));
        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                .addContainerGap(856, Short.MAX_VALUE)
                .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlMainLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(srlPR, javax.swing.GroupLayout.PREFERRED_SIZE, 813, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(175, Short.MAX_VALUE)))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(653, Short.MAX_VALUE))
            .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlMainLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(srlPR, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblPRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPRMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblPRMouseClicked

    private void tblPRMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPRMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tblPRMouseReleased

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        NewPR newPR = new NewPR(this, true, username);
        newPR.setLocationRelativeTo(this);
        newPR.setVisible(true);
        PR();
    }//GEN-LAST:event_btnNewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNew;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JScrollPane srlPR;
    private javax.swing.JTable tblPR;
    // End of variables declaration//GEN-END:variables
}
