package com.owsb.poms.ui.admin.Orders;

import com.owsb.poms.system.model.*;
import com.owsb.poms.system.model.User.Admin;
import com.owsb.poms.system.model.company.Bank;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.*;

public class ProcessPayment extends javax.swing.JDialog {
    private JDialog parent;
    private PurchaseOrder po;
    private Bank bank;
    private String processBy;

    public ProcessPayment(javax.swing.JDialog parent, boolean modal, PurchaseOrder po, Admin admin) {
        super(parent, modal);
        initComponents();
        
        this.parent = parent;
        this.po = po;
        this.processBy = admin.getUID();
        
        setTitle(String.format("Process Paymeny (%s)", po.getPOID()));
        lblPOID.setText(po.getPOID());
        lblSupplierID.setText(po.getSupplierID());
        lblSupplierName.setText(Supplier.getNameById(po.getSupplierID()));
        lblTotalPrice.setText(String.format("RM %.2f", po.getTotalPrice()));
        lblDate.setText(LocalDate.now().format(DateTimeFormatter.ofPattern("dd MMMM yyyy")));
        lblProcessBy.setText(String.format("%s  %s", admin.getUID(), admin.getUsername()));
        lblAccountNumber.setText("");
        
        List<Bank> banks = Bank.toList();
        
        for (Bank bank : banks){
            if (bank.isIsDeleted() == false) cmbBank.addItem(bank.getBankName());
        }
        
        cmbBank.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblPOID = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblSupplierID = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblSupplierName = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblTotalPrice = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblProcessBy = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cmbBank = new javax.swing.JComboBox<>();
        lblAccountNumber = new javax.swing.JLabel();
        txtAccountNumber = new javax.swing.JTextField();
        txtBankTo = new javax.swing.JTextField();
        btnProcessPayment = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDetails = new javax.swing.JTextArea();
        btnCancel = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlMain.setBackground(new java.awt.Color(244, 213, 188));

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Process Payment");

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("ID:");

        lblPOID.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        lblPOID.setForeground(new java.awt.Color(0, 0, 0));
        lblPOID.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPOID.setText("[POID]");

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Supplier ID:");

        lblSupplierID.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        lblSupplierID.setForeground(new java.awt.Color(0, 0, 0));
        lblSupplierID.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSupplierID.setText("[SupplierID]");

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Supplier:");

        lblSupplierName.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        lblSupplierName.setForeground(new java.awt.Color(0, 0, 0));
        lblSupplierName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSupplierName.setText("[SupplierName]");

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Total Price:");

        lblTotalPrice.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        lblTotalPrice.setForeground(new java.awt.Color(0, 0, 0));
        lblTotalPrice.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTotalPrice.setText("[TotalPrice]");
        lblTotalPrice.setToolTipText("");

        jLabel10.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Date:");

        lblDate.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        lblDate.setForeground(new java.awt.Color(0, 0, 0));
        lblDate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDate.setText("[Date]");
        lblDate.setToolTipText("");

        jLabel11.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Proceed By:");

        lblProcessBy.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        lblProcessBy.setForeground(new java.awt.Color(0, 0, 0));
        lblProcessBy.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblProcessBy.setText("[ProceedBy]");
        lblProcessBy.setToolTipText("");

        jLabel12.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("From:");

        jLabel13.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Account Number:");

        jLabel14.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("To:");

        jLabel15.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Account Number:");

        cmbBank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBankActionPerformed(evt);
            }
        });

        lblAccountNumber.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        lblAccountNumber.setForeground(new java.awt.Color(0, 0, 0));
        lblAccountNumber.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAccountNumber.setText("[Account Number]");
        lblAccountNumber.setToolTipText("");

        btnProcessPayment.setBackground(new java.awt.Color(255, 153, 0));
        btnProcessPayment.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        btnProcessPayment.setForeground(new java.awt.Color(252, 251, 249));
        btnProcessPayment.setText("Process Payment");
        btnProcessPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessPaymentActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Details:");

        txtDetails.setColumns(20);
        txtDetails.setRows(5);
        jScrollPane1.setViewportView(txtDetails);

        btnCancel.setBackground(new java.awt.Color(255, 153, 0));
        btnCancel.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(252, 251, 249));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("Amount:");

        jLabel18.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("RM");

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addComponent(btnProcessPayment)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlMainLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(217, 217, 217))
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15))
                                .addGap(73, 73, 73))
                            .addGroup(pnlMainLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(135, 135, 135)))
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(cmbBank, 0, 223, Short.MAX_VALUE)
                            .addComponent(lblSupplierID)
                            .addComponent(lblPOID)
                            .addComponent(lblSupplierName)
                            .addComponent(lblTotalPrice)
                            .addComponent(lblDate)
                            .addComponent(lblProcessBy)
                            .addComponent(lblAccountNumber)
                            .addComponent(txtAccountNumber)
                            .addComponent(txtBankTo)
                            .addGroup(pnlMainLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAmount)))))
                .addContainerGap(85, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(38, 38, 38)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblPOID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblSupplierID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblSupplierName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblTotalPrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lblProcessBy))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cmbBank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lblAccountNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtBankTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnProcessPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(103, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbBankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBankActionPerformed
        if (cmbBank.getSelectedIndex() >= 0){
            bank = Bank.getBankByName(cmbBank.getSelectedItem().toString());
            lblAccountNumber.setText(String.valueOf(bank.getAccountNumber()));
        }
    }//GEN-LAST:event_cmbBankActionPerformed

    private void btnProcessPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessPaymentActionPerformed
        if (cmbBank.getSelectedIndex() == -1){
            JOptionPane.showMessageDialog(this, "Please select a bank", "Invalid Action", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String bankTo = txtBankTo.getText().trim();
        long accountNumber;
        double amount;
        double paid = po.getTransactions().isEmpty() ? 0 : po.getTransactions().stream().mapToDouble(Transaction::getAmount).sum();
        double hasToPay = po.getTotalPrice() - paid;
        String details = txtDetails.getText().isBlank() ? "None" : txtDetails.getText().trim();
        
        if (bankTo.isBlank() || bankTo.length() < 5){
            JOptionPane.showMessageDialog(this, "Invalid Bank Name", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try{
            accountNumber = Long.parseLong(txtAccountNumber.getText().trim());
        } catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Invalid Account Number", "Error", JOptionPane.ERROR_MESSAGE);
            return; 
        }
        
        if (accountNumber < 9999999){
            JOptionPane.showMessageDialog(this, "Invalid Account Number", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try{
            amount = Double.parseDouble(txtAmount.getText().trim());
        } catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Invalid Amount", "Error", JOptionPane.ERROR_MESSAGE);
            return; 
        }
        
        if (amount > hasToPay || amount <= 0){
            JOptionPane.showMessageDialog(this, "Invalid Amount", "Error", JOptionPane.ERROR_MESSAGE);
            return; 
        }
        
        int result = JOptionPane.showConfirmDialog(this, "Are you sure to process payment?", "Process Payment", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (result == JOptionPane.YES_OPTION){
            Transaction transaction = new Transaction(po.getPOID(), bank.getBankName(), bank.getAccountNumber(), bankTo, accountNumber, amount, details, processBy);
            transaction.add();
            
                String message = po.isFullyPaid() ? 
                        String.format(
                                "Process Payment Successfully!%n"
                              + "Order %s has been set as Completed!", 
                                po.getPOID()
                        ):
                        String.format("Process Payment Successfully!%n"
                              + "Total    : RM %.2f%n"
                              + "Paid     : RM %.2f%n"
                              + "Remaining: RM %.2f", 
                                po.getTotalPrice(),
                                paid,
                                hasToPay
                        );

                if (po.isFullyPaid()){
                    po.setStatus(PurchaseOrder.Status.COMPLETED);
                    po.updateStatus();
                }

                JOptionPane.showMessageDialog(this, message);

                dispose();
                parent.dispose();
            }
        dispose();
    }//GEN-LAST:event_btnProcessPaymentActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnProcessPayment;
    private javax.swing.JComboBox<String> cmbBank;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAccountNumber;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblPOID;
    private javax.swing.JLabel lblProcessBy;
    private javax.swing.JLabel lblSupplierID;
    private javax.swing.JLabel lblSupplierName;
    private javax.swing.JLabel lblTotalPrice;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JTextField txtAccountNumber;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtBankTo;
    private javax.swing.JTextArea txtDetails;
    // End of variables declaration//GEN-END:variables
}
