package com.owsb.poms.ui.admin.Dashboard;

import com.owsb.poms.system.model.company.Bank;
import java.util.List;
import javax.swing.JOptionPane;

public class BankSetting extends javax.swing.JDialog {
    private List<Bank> banks;
    private Bank bank;
    private boolean newBank;

    public BankSetting(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        banks = Bank.toList();
        
        for (Bank bank : banks){
            if (bank.isIsDeleted() == false) cmbBank.addItem(bank.getBankName());
        }
        
        cmbBank.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbBank = new javax.swing.JComboBox<>();
        txtBank = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAccountNumber = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlMain.setBackground(new java.awt.Color(255, 204, 204));

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Bank Setting");

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Bank:");

        cmbBank.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "New" }));
        cmbBank.setSelectedItem(null);
        cmbBank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBankActionPerformed(evt);
            }
        });

        txtBank.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Account Number:");

        txtAccountNumber.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N

        btnSave.setBackground(new java.awt.Color(255, 153, 0));
        btnSave.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(252, 251, 249));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(255, 153, 0));
        btnDelete.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(252, 251, 249));
        btnDelete.setText("Delete Account");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(pnlMainLayout.createSequentialGroup()
                            .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addGap(36, 36, 36)
                            .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtBank, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmbBank, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(pnlMainLayout.createSequentialGroup()
                            .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDelete)))
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel6)))
                .addGap(37, 37, 37))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbBank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbBankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBankActionPerformed
        if (cmbBank.getSelectedIndex() == -1){
            txtBank.setVisible(false);
        }
        else if (cmbBank.getSelectedIndex() == 0){
            newBank = true;
            txtBank.setVisible(true);
            txtBank.getParent().revalidate();
            txtBank.getParent().repaint();
            txtAccountNumber.setText("");
        }
        else{
            newBank = false;
            txtBank.setVisible(false);
            txtBank.getParent().revalidate();
            txtBank.getParent().repaint();
            bank = Bank.getBankByName(cmbBank.getSelectedItem().toString());
            txtAccountNumber.setText(String.valueOf(bank.getAccountNumber()));
        }
    }//GEN-LAST:event_cmbBankActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (cmbBank.getSelectedIndex() == -1){
            JOptionPane.showMessageDialog(this, "Please select a bank", "Invalid Action", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String name = cmbBank.getSelectedIndex() != 0 && cmbBank.getSelectedItem() != null ? 
                cmbBank.getSelectedItem().toString() : txtBank.getText().trim();
        
        long accountNumber;
        
        try{
            accountNumber = Long.parseLong(txtAccountNumber.getText().trim());
        } catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Invalid Account Number", "Error", JOptionPane.ERROR_MESSAGE);
            return; 
        }
        
        if (newBank){
            if (banks.stream().anyMatch(bank -> bank.getBankName().equalsIgnoreCase(txtBank.getText())) ||
            banks.stream().anyMatch(bank -> String.valueOf(bank.getAccountNumber()).equalsIgnoreCase(String.valueOf(accountNumber)))){
                JOptionPane.showMessageDialog(this, "Bank already existed", "Invalid Action", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        
        if (name.isBlank() || name.length() < 5){
            JOptionPane.showMessageDialog(this, "Invalid Bank Name", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (accountNumber < 9999999){
            JOptionPane.showMessageDialog(this, "Invalid Account Number", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int result = JOptionPane.showConfirmDialog(this, "Are you sure to make this change?", "Save Change", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (result == JOptionPane.YES_OPTION){
            if (newBank){
                Bank bank = new Bank();
                bank.setBankName(name);
                bank.setAccountNumber(accountNumber);
                bank.add();
                JOptionPane.showMessageDialog(this, "Successfully added a new bank account!");
            }
            else {
                bank.setAccountNumber(accountNumber);
                bank.update();
                JOptionPane.showMessageDialog(this, "Successfully change the account number!");
            }
            
            dispose();
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (cmbBank.getSelectedIndex() == -1){
            JOptionPane.showMessageDialog(this, "Please select a bank", "Invalid Action", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (newBank || bank.getAccountNumber() != Long.parseLong(txtAccountNumber.getText())){
            JOptionPane.showMessageDialog(this, "Account doesn't exist", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int result = JOptionPane.showConfirmDialog(this, "Are you sure to delete this account?", "Delete Account", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (result == JOptionPane.YES_OPTION){
            bank.setIsDeleted(true);
            bank.update();

            JOptionPane.showMessageDialog(this, String.format("Successfully deleted this account:%nBank Name: %s%nAccount Number: %s", bank.getBankName(), bank.getAccountNumber()));
            dispose();
        }
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbBank;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JTextField txtAccountNumber;
    private javax.swing.JTextField txtBank;
    // End of variables declaration//GEN-END:variables
}
