package com.owsb.poms.ui.admin.Dashboard;

import com.owsb.poms.system.model.*;
import java.time.format.DateTimeFormatter;
import javax.swing.SwingConstants;
import javax.swing.table.*;

public class StockUpdateReportViewer extends javax.swing.JDialog {
    private Report report;
    private DefaultTableModel reportModel = new DefaultTableModel(){
       public boolean isCellEditable(int row, int column){
           return false;
       } 
    } ;
    private String[] reportColumnName = {"ID", "Name", "Category", "Type", "Previous", "Change", "New"};

    public StockUpdateReportViewer(javax.swing.JDialog parent, boolean modal, Report report) {
        super(parent, modal);
        initComponents();
        
        setTitle(String.format("%s (%s)", report.getReportID(), report.getDateTime().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"))));
        
        this.report = report;
        Report();
    }
    
    private void Report(){
        reportModel.setRowCount(0);
        
        reportModel.setColumnIdentifiers(reportColumnName);
        JTableHeader header = tblReport.getTableHeader();
        header.setBackground(new java.awt.Color(255, 255, 204));
        
        srlReport.getViewport().setBackground(new java.awt.Color(255, 255, 204));
        
        tblReport.getColumnModel().getColumn(0).setPreferredWidth(80);
        tblReport.getColumnModel().getColumn(1).setPreferredWidth(220);
        tblReport.getColumnModel().getColumn(2).setPreferredWidth(100);
        tblReport.getColumnModel().getColumn(3).setPreferredWidth(150);
        
        String fileName = report.getReportID()+ ".txt";
        var list = StockUpdateReport.read(fileName);
        
        for (StockUpdateReport sup : list) {
            reportModel.addRow(new String[]{
                sup.getItemID(),
                sup.getItemName(),
                sup.getItemCategory(),
                sup.getItemType(),
                report.getMessage().equals("Stock Increasing") ? 
                        String.valueOf(sup.getStock() - sup.getUpdate()) : 
                        String.valueOf(sup.getStock() + sup.getUpdate()),
                String.valueOf(sup.getUpdate()),
                String.valueOf(sup.getStock()),
            });
        }
        
        // Create a single “center” renderer:
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);

        // Apply it as the default for any Object‐typed cell:
        tblReport.setDefaultRenderer(Object.class, centerRenderer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        srlReport = new javax.swing.JScrollPane();
        tblReport = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlMain.setBackground(new java.awt.Color(255, 204, 204));

        tblReport.setBackground(new java.awt.Color(255, 255, 204));
        tblReport.setModel(reportModel);
        tblReport.setGridColor(java.awt.Color.gray);
        tblReport.setRowSelectionAllowed(false);
        tblReport.setSelectionBackground(new java.awt.Color(255, 153, 153));
        tblReport.setShowGrid(true);
        srlReport.setViewportView(tblReport);

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(srlReport, javax.swing.GroupLayout.PREFERRED_SIZE, 813, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(srlReport, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlMain;
    private javax.swing.JScrollPane srlReport;
    private javax.swing.JTable tblReport;
    // End of variables declaration//GEN-END:variables
}
