package com.owsb.poms.ui.admin.Inventory;

import com.owsb.poms.system.model.Item;
import javax.swing.*;


public class UpdateStatus extends javax.swing.JDialog {
    private Item item;

    public UpdateStatus(java.awt.Frame parent, boolean modal, Item item) {
        super(parent, modal);
        initComponents();
        
        this.item = item;
        setTitle(String.format("Update Status: %s %s", item.getItemID(), item.getItemName()));
        ButtonGroup bg = new ButtonGroup();
        bg.add(radSufficient);
        bg.add(radShortage);
        
        switch (item.getStatus()) {
            case SUFFICIENT -> radSufficient.setSelected(true);
            case SHORTAGE -> radShortage.setSelected(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        radSufficient = new javax.swing.JRadioButton();
        radShortage = new javax.swing.JRadioButton();
        btnOK = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlMain.setBackground(new java.awt.Color(204, 204, 255));

        radSufficient.setBackground(new java.awt.Color(204, 204, 255));
        radSufficient.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        radSufficient.setForeground(new java.awt.Color(0, 0, 0));
        radSufficient.setText("Sufficient");

        radShortage.setBackground(new java.awt.Color(204, 204, 255));
        radShortage.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        radShortage.setForeground(new java.awt.Color(0, 0, 0));
        radShortage.setText("Shortage");

        btnOK.setBackground(new java.awt.Color(255, 204, 204));
        btnOK.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        btnOK.setForeground(new java.awt.Color(0, 0, 0));
        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(255, 204, 204));
        btnCancel.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(0, 0, 0));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(radShortage, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radSufficient, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOK, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(radSufficient)
                .addGap(18, 18, 18)
                .addComponent(radShortage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOK)
                    .addComponent(btnCancel))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        if (!radSufficient.isSelected() && !radShortage.isSelected()){
            JOptionPane.showMessageDialog(this, "Please select a status", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int result = JOptionPane.showConfirmDialog(this, "Are you sure to change this item's status?", "Update Status", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (result == JOptionPane.YES_OPTION) {
            if (radSufficient.isSelected() || radShortage.isSelected()) {
                Item.Status newStatus = radSufficient.isSelected() ? Item.Status.SUFFICIENT : Item.Status.SHORTAGE;
                item.setStatus(newStatus);
                item.updateStatus();
                JOptionPane.showMessageDialog(this, "Successfully changed the status to " + newStatus.name().charAt(0) + newStatus.name().substring(1).toLowerCase() + "!");
                this.dispose();
            }
        }

    }//GEN-LAST:event_btnOKActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOK;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JRadioButton radShortage;
    private javax.swing.JRadioButton radSufficient;
    // End of variables declaration//GEN-END:variables
}
